---
- name: Verify
  hosts: all
  tasks:
    - name: test connection
      ping:

    - name: Gather service facts
      service_facts:
      register: services_state

    - name: Verify if the gophish service is running
      assert:
        that: services_state.ansible_facts.services["gophish.service"].state == "running"

    - name: Check gophish phising page
      uri:
        url: http://127.0.0.1:80
        status_code: 404

    - name: Check gophish admin page
      uri:
        url: https://127.0.0.1:3333/login
        status_code: 200
        validate_certs: no
